// 知乎
export const ZHIHU_SET_ARTICLES = 'ZHIHU_SET_ARTICLES'
export const ZHIHU_SET_DATE_POINTER = 'ZHIHU_SET_DATE_POINTER'
// 今日头条
export const NEWS_SET_ITEMS = 'NEWS_SET_ITEMS'
// 微信精选
export const WEIXIN_SET_ITEMS = 'WEIXIN_SET_ITEMS'
